version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    volumes:
      - ./es-data/:/usr/share/elasticsearch/data
      - ./es-config/:/usr/share/elasticsearch/config/
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=logging-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    restart: unless-stopped
    ports:
      - 5601:5601
    networks:
      - elk

networks:
  elk:
    driver: bridge
